dataset_path : "/home/shreeram/workspace/ambl/custom_efficent_autodistillation/Dataset"
categories: ["Rock Paper Scissors.v1-raw-300x300.folder"]
# categories: ["dataset_2_kana_update2"] 
# categories: ["dataset_0_region_update2"] 
network_architecture: "efficientnet_b0"
# network_architecture: "efficientnet_b3"
input_img_size: 128
lr: 0.0001
end_lr: 0.00001  # minimum learning rate 
batch_size: 16
num_workers: 4
epochs: 5  #50
early_stopping_patience: 3 #10
#device uses GPU if available else uses cpu by default
project_base_dir: "runs" # Base project directory
# project_name: "exp"
project_name: "rock_paper_scissor_test"


# For teacher student training
teacher_student_distillation: False
temperature: 3.0  # Temperature for distillation 3.0 Default (try higher temperature 5.0)
alpha: 0.7  # Weighting for soft vs. hard target loss  Default 0.7 (try 0.5)

