dataset_path : "/home/shreeram/workspace/ambl/custom_efficent_autodistillation/Dataset"
categories: ["dataset_2_kana_update2"] 
network_architecture: "efficientnet_b7"
input_img_size: 128
lr: 0.0001  # starting
end_lr: 0.00001  # minimum learning rate 
batch_size: 32
num_workers: 4
epochs: 50  #50
early_stopping_patience: 10 #10
project_base_dir: "runs" # Base project directory
project_name: "Dataset_2_kana_update2_customized_efficentnetB7"
# For teacher student training
teacher_student_distillation: False
temperature: 3.0  # Temperature for distillation 3.0 Default (try higher temperature 5.0)
alpha: 0.7  # Weighting for soft vs. hard target loss  Default 0.7 (try 0.5)

